<a href="https://colab.research.google.com/github/shameer-phy/ML/blob/main/Hackathons/univ.ai/Loan_Default.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

In [3]:
from google.colab import drive 

drive.mount("/content/gdrive") 

Mounted at /content/gdrive


In [4]:
# Lets read the training dataset and tes dataset

ld = pd.read_csv('/content/gdrive/My Drive/Datasets/univ.ai/Training Data.csv')
 
ld_test = pd.read_csv('/content/gdrive/My Drive/Datasets/univ.ai/Test Data.csv')


In [5]:
ld.head()

ld.count()

ld.dtypes

Id                      int64
income                  int64
age                     int64
experience              int64
married                object
house_ownership        object
car_ownership          object
profession             object
city                   object
state                  object
current_job_years       int64
current_house_years     int64
risk_flag               int64
dtype: object

In [ ]:
for x in ld.columns:
    print('\n')
    print(x)
    print(len(ld[x].unique()))
    print(ld[x].value_counts())



Id
252000
2047     1
64074    1
59976    1
37447    1
39494    1
        ..
95620    1
85379    1
83330    1
89473    1
2049     1
Name: Id, Length: 252000, dtype: int64


income
41917
7936020    77
9775375    71
1996629    71
9345456    70
7638998    40
           ..
5446449     1
7330601     1
3377955     1
2779935     1
7907349     1
Name: income, Length: 41917, dtype: int64


age
59
27    5197
66    5092
48    4967
33    4921
41    4827
45    4806
54    4785
68    4772
35    4644
50    4624
69    4617
76    4585
55    4563
25    4543
72    4534
79    4505
60    4504
59    4498
53    4490
47    4483
30    4468
78    4455
22    4430
34    4414
57    4394
58    4368
56    4344
24    4326
23    4322
62    4311
31    4257
70    4251
61    4235
40    4233
43    4206
21    4205
49    4203
26    4156
37    4153
71    4149
42    4134
64    4132
29    4109
67    3995
65    3969
74    3954
63    3942
77    3916
28    3901
32    3834
75    3829
39    3800
38    3793
46    3627
44    3622
73 

In [ ]:
obj_cols = ld.select_dtypes(include=['object'])
obj_cols

married house_ownership  ...                 city           state
0        single          rented  ...                 Rewa  Madhya_Pradesh
1        single          rented  ...             Parbhani     Maharashtra
2       married          rented  ...            Alappuzha          Kerala
3        single          rented  ...          Bhubaneswar          Odisha
4        single          rented  ...  Tiruchirappalli[10]      Tamil_Nadu
...         ...             ...  ...                  ...             ...
251995   single          rented  ...              Kolkata     West_Bengal
251996   single          rented  ...                 Rewa  Madhya_Pradesh
251997   single          rented  ...      Kalyan-Dombivli     Maharashtra
251998   single          rented  ...          Pondicherry      Puducherry
251999   single          rented  ...                Avadi      Tamil_Nadu

[252000 rows x 6 columns]

In [ ]:
for x in obj_cols.columns:
  ld[x] = pd.factorize(ld[x])[0]

In [ ]:
ld.head()

Id   income  age  ...  current_job_years  current_house_years  risk_flag
0   1  1303835   23  ...                  3                   13          0
1   2  7574516   40  ...                  9                   13          0
2   3  3991815   66  ...                  4                   10          0
3   4  6256451   41  ...                  2                   12          1
4   5  5768871   47  ...                  3                   14          1

[5 rows x 13 columns]

In [ ]:
for x in obj_cols.columns:
  ld_test[x] = pd.factorize(ld_test[x])[0]
ld_test.head()

id   income  age  ...  state  current_job_years  current_house_years
0   1  7393090   59  ...      0                  4                   13
1   2  1215004   25  ...      1                  5                   10
2   3  8901342   50  ...      1                  9                   14
3   4  1944421   49  ...      1                  3                   12
4   5    13429   25  ...      0                 13                   11

[5 rows x 12 columns]

#Lets split X,Y as well as train and test sets

In [ ]:
X = ld.drop(['Id','risk_flag'],axis=1)
Y = ld['risk_flag']

In [ ]:
Xtest = ld_test.drop(['id'],axis=1)

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=13)

In [ ]:
xtrain.shape
ytrain.shape
xtest.shape
ytest.shape

(63000,)

#Lets fit a Logistic model and check accuracy

In [ ]:
#function to write report
def write_report(name):
  report = pd.concat([ld_test['id'],pd.DataFrame(ypred,columns=['risk_flag'])],axis=1)
  report.to_csv('/content/gdrive/My Drive/Datasets/univ.ai/' + name ,index=False)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
log_mod = LogisticRegression()
scores = cross_val_score(log_mod,xtrain,ytrain,scoring='roc_auc')
scores


array([0.50196728, 0.49528195, 0.50506802, 0.50772664, 0.50412322])

In [ ]:
ypred = log_mod.fit(xtrain,ytrain).predict(xtest)

In [ ]:
roc_auc_score(ytest,ypred)

0.5

In [ ]:
auc = cross_val_score(log_mod,X,Y,scoring='accuracy')
auc

array([0.87700397, 0.87700397, 0.87700397, 0.87700397, 0.87698413])

#Lets fit a DecisionTree and check

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
scores = cross_val_score(DT,xtrain,ytrain,scoring='roc_auc')
scores

array([0.84760544, 0.8496886 , 0.85379602, 0.85253173, 0.85345652])

In [ ]:
ypred = DT.fit(xtrain,ytrain).predict(xtest)
roc_auc_score(ytest,ypred)

0.7502345272877026

In [ ]:
auc = cross_val_score(DT,X,Y,scoring='accuracy')
auc

array([0.93107143, 0.92253968, 0.90876984, 0.88700397, 0.73238095])

#Decions tree looks more promising than logistic
#Lets try Randomforest and check

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(max_features = 0.5,n_estimators=200)
scores = cross_val_score(RF,xtrain,ytrain,scoring='roc_auc')
scores

array([0.93747953, 0.93765926, 0.93854006, 0.93925197, 0.9372049 ])

In [ ]:
ypred = RF.fit(xtrain,ytrain).predict(xtest)
roc_auc_score(ytest,ypred)

0.7410637183719415

In [ ]:
ypred = RF.fit(xtrain,ytrain).predict(Xtest)

In [ ]:
write_report('rf_output.csv')

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(max_features = 0.6,n_estimators=100)
auc_roc = cross_val_score(RF,X,Y,scoring='roc_auc')
auc_roc

array([0.97495546, 0.96832583, 0.95781029, 0.93612737, 0.65070217])

In [ ]:

RF = RandomForestClassifier(max_features = 0.5,n_estimators=100)
RF.fit(X,Y)
ypred = RF.predict(Xtest)

In [ ]:
report = pd.concat([ld_test['id'],pd.DataFrame(ypred,columns=['risk_flag'])],axis=1)
report

id  risk_flag
0          1          0
1          2          0
2          3          0
3          4          0
4          5          0
...      ...        ...
27995  27996          0
27996  27997          0
27997  27998          0
27998  27999          0
27999  28000          0

[28000 rows x 2 columns]

In [ ]:
report.to_csv('/content/gdrive/My Drive/Datasets/univ.ai/output.csv',index=False)

#Take the oupput file of logistic reg

In [ ]:
log_mod = LogisticRegression()
log_mod.fit(X,Y)
ypred = log_mod.predict(Xtest)
report = pd.concat([ld_test['id'],pd.DataFrame(ypred,columns=['risk_flag'])],axis=1)
report.to_csv('/content/gdrive/My Drive/Datasets/univ.ai/logmod_output.csv',index=False)

In [ ]:
write_report('logmod1.csv')

#Lets try KNN and check

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=17)
scores = cross_val_score(knn,xtrain,ytrain,scoring='roc_auc')
scores

array([0.88673756, 0.88626517, 0.88754896, 0.89081704, 0.88968175])

In [ ]:
knn.fit(xtrain,ytrain)
ypred = knn.predict(xtest)
roc_auc_score(ytest,ypred)

0.745858353659777

In [ ]:
ypred = knn.predict(Xtest)
write_report('knn_output.csv')

In [ ]:
from sklearn.ensemble import BaggingClassifier
knn = KNeighborsClassifier(n_neighbors=17)
bc = BaggingClassifier(base_estimator=knn,n_estimators=100)
bc.fit(xtrain,ytrain)


AttributeError: ignored

In [ ]:
ypred = bc.predict(xtest)
roc_auc_score(ytest,ypred)

0.7466217025318687

In [ ]:
from sklearn.ensemble import BaggingClassifier
knn = KNeighborsClassifier(n_neighbors=17)
bc = BaggingClassifier(base_estimator=knn,n_estimators=100)
bc.fit(X,Y)
ypred = bc.predict(xtest)
roc_auc_score(ytest,ypred)

0.7568753689598168

In [ ]:
ypred = bc.predict(Xtest)
write_report('knnfullbagging_output.csv')

#Lets apply boosting on different algos

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
dt = DecisionTreeClassifier()
abc = AdaBoostClassifier(n_estimators=200,learning_rate=0.3)

In [ ]:
abc.fit(xtrain,ytrain)
ypred = abc.predict(xtest)
roc_auc_score(ytest,ypred)

0.500578927055191

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_features=0.5,n_estimators=100)
abc = AdaBoostClassifier(base_estimator=rf,n_estimators=50,random_state=13)

In [ ]:
abc.fit(xtrain,ytrain)
ypred = abc.predict(xtest)
roc_auc_score(ytest,ypred)

0.7434485039700396

In [ ]:
ypred = abc.predict(Xtest)
write_report('ada_RF_output.csv')

In [ ]:
#Applying gradient boosting

from sklearn.ensemble import GradientBoostingClassifier
dt = DecisionTreeClassifier()
gbc = GradientBoostingClassifier(n_estimators=200)

In [ ]:
gbc.fit(xtrain,ytrain)
ypred = gbc.predict(xtest)
roc_auc_score(ytest,ypred)

0.502400041394013

#applying boost on logistic

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
from sklearn.ensemble import RandomForestClassifier
abc = AdaBoostClassifier(base_estimator=lr,n_estimators=200,learning_rate=0.5)

In [ ]:
abc.fit(xtrain,ytrain)
ypred = abc.predict(xtest)
roc_auc_score(ytest,ypred)

0.5

#Lets try Naive Bayes and check

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(xtrain,ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
ypred = mnb.predict(xtest)
roc_auc_score(ytest,ypred)

0.5133683052362875

In [ ]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(xtrain,ytrain)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [ ]:
ypred = bnb.predict(xtest)
roc_auc_score(ytest,ypred)

0.5

# Lets import the data again and apply chi-square test to eliminate categorical columns


In [6]:
ldnew = pd.read_csv('/content/gdrive/My Drive/Datasets/univ.ai/Training Data.csv')
 
ldnew_test = pd.read_csv('/content/gdrive/My Drive/Datasets/univ.ai/Test Data.csv')

In [7]:
#function to write report
def write_report(name):
  report = pd.concat([ldnew_test['id'],pd.DataFrame(ypred,columns=['risk_flag'])],axis=1)
  report.to_csv('/content/gdrive/My Drive/Datasets/univ.ai/' + name ,index=False)

In [8]:
ldnew.head()

Id   income  age  ...  current_job_years current_house_years risk_flag
0   1  1303835   23  ...                  3                  13         0
1   2  7574516   40  ...                  9                  13         0
2   3  3991815   66  ...                  4                  10         0
3   4  6256451   41  ...                  2                  12         1
4   5  5768871   47  ...                  3                  14         1

[5 rows x 13 columns]

In [9]:
obj_cols = ldnew.select_dtypes(include=['object'])
obj_cols = obj_cols.columns

In [10]:
!pip install researchpy
def chi2test(x,y):
  import researchpy as rp
  t = rp.crosstab(ldnew[x],ldnew[y],test='chi-square')
  if t[1].iloc[1,1] < 0.05:
    print(t[0])
    print('Depedent. Drop a variable')
  else:
    print('Independent. Keep both')

In [11]:
chi2test(obj_cols[0],obj_cols[1])

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


                house_ownership                       
house_ownership    norent_noown  owned  rented     All
married                                               
married                     595    923   24210   25728
single                     6589  11995  207688  226272
All                        7184  12918  231898  252000
Depedent. Drop a variable


In [12]:
chi2test(obj_cols[2],obj_cols[1])

Independent. Keep both


In [13]:
drop_cols = []
drop_cols.append(obj_cols[0])

In [14]:
chi2test(obj_cols[3],obj_cols[1])

                           house_ownership                       
house_ownership               norent_noown  owned  rented     All
profession                                                       
Air_traffic_controller                 158    206    4917    5281
Analyst                                122    182    4364    4668
Architect                              143    441    4073    4657
Army_officer                           190    292    4179    4661
Artist                                  58    300    4503    4861
Aviator                                 93    438    4227    4758
Biomedical_Engineer                    248    252    4627    5127
Chartered_Accountant                   132    250    4111    4493
Chef                                    94    154    4387    4635
Chemical_engineer                      201    292    4712    5205
Civil_engineer                         138    340    4138    4616
Civil_servant                          126    263    4024    4413
Comedian  

In [15]:
drop_cols.append(obj_cols[3])

In [16]:
chi2test(obj_cols[4],obj_cols[1])

                 house_ownership                       
house_ownership     norent_noown  owned  rented     All
city                                                   
Adoni                          2      5     946     953
Agartala                      40     71     698     809
Agra                           3      7    1002    1012
Ahmedabad                      2     42     605     649
Ahmednagar                    43     39     563     645
...                          ...    ...     ...     ...
Vijayawada                    79    115     978    1172
Visakhapatnam[4]              37      8     926     971
Warangal[11][12]               3     11     445     459
Yamunanagar                  107      4     548     659
All                         7184  12918  231898  252000

[318 rows x 4 columns]
Depedent. Drop a variable


In [18]:
#drop_cols.append(obj_cols[4])
drop_cols.append(obj_cols[5])

In [ ]:
chi2test(obj_cols[5],obj_cols[1])

                  house_ownership                       
house_ownership      norent_noown  owned  rented     All
state                                                   
Andhra_Pradesh                752   1069   23476   25297
Assam                         133    222    6707    7062
Bihar                         657    805   18318   19780
Chandigarh                     41     45     570     656
Chhattisgarh                  125    214    3495    3834
Delhi                         236    406    4848    5490
Gujarat                       405    628   10375   11408
Haryana                       253    387    7250    7890
Himachal_Pradesh                7     43     783     833
Jammu_and_Kashmir              47     11    1722    1780
Jharkhand                     173    520    8272    8965
Karnataka                     361    729   10765   11855
Kerala                        206    150    5449    5805
Madhya_Pradesh                314    863   12945   14122
Maharashtra                   5

In [20]:
obj_cols
#drop_cols.remove('profession')
drop_cols.append('house_ownership')

In [21]:
drop_cols

['married', 'city', 'state', 'house_ownership']

In [22]:
ldnew = ldnew.drop(drop_cols,axis=1)

In [23]:
ldnew = ldnew.drop('Id',axis=1)
ldnew.head()

income  age  experience  ... current_job_years current_house_years  risk_flag
0  1303835   23           3  ...                 3                  13          0
1  7574516   40          10  ...                 9                  13          0
2  3991815   66           4  ...                 4                  10          0
3  6256451   41           2  ...                 2                  12          1
4  5768871   47          11  ...                 3                  14          1

[5 rows x 8 columns]

In [24]:
ldnew.corr()

income       age  ...  current_house_years  risk_flag
income               1.000000 -0.000652  ...            -0.002397  -0.003091
age                 -0.000652  1.000000  ...            -0.020134  -0.021809
experience           0.006422 -0.001118  ...             0.019309  -0.034523
current_job_years    0.007045  0.002154  ...             0.005372  -0.016942
current_house_years -0.002397 -0.020134  ...             1.000000  -0.004375
risk_flag           -0.003091 -0.021809  ...            -0.004375   1.000000

[6 rows x 6 columns]

In [25]:
ldnew = ldnew.drop('current_job_years',axis=1)
ldnew.head()

income  age  ...  current_house_years risk_flag
0  1303835   23  ...                   13         0
1  7574516   40  ...                   13         0
2  3991815   66  ...                   10         0
3  6256451   41  ...                   12         1
4  5768871   47  ...                   14         1

[5 rows x 7 columns]

In [26]:
req_cols = list(ldnew.columns)
req_cols.remove('risk_flag')
ldnew_test = ldnew_test[req_cols]
ldnew_test.head()

income  age  experience car_ownership   profession  current_house_years
0  7393090   59          19            no    Geologist                   13
1  1215004   25           5            no  Firefighter                   10
2  8901342   50          12            no       Lawyer                   14
3  1944421   49           9           yes      Analyst                   12
4    13429   25          18           yes     Comedian                   11

In [27]:
ldnew['profession'] = pd.factorize(ldnew['profession'])[0]
ldnew.head()

income  age  experience  ... profession  current_house_years  risk_flag
0  1303835   23           3  ...          0                   13          0
1  7574516   40          10  ...          1                   13          0
2  3991815   66           4  ...          2                   10          0
3  6256451   41           2  ...          1                   12          1
4  5768871   47          11  ...          3                   14          1

[5 rows x 7 columns]

In [28]:
ldnew_test['profession'] = pd.factorize(ldnew_test['profession'])[0]
ldnew_test.head()

income  age  experience car_ownership  profession  current_house_years
0  7393090   59          19            no           0                   13
1  1215004   25           5            no           1                   10
2  8901342   50          12            no           2                   14
3  1944421   49           9           yes           3                   12
4    13429   25          18           yes           4                   11

In [29]:
ldnew['car_ownership'] = pd.factorize(ldnew['car_ownership'])[0]
ldnew_test['car_ownership'] = pd.factorize(ldnew_test['car_ownership'])[0]

In [30]:
ldnew.head()
ldnew_test.head()

income  age  experience  car_ownership  profession  current_house_years
0  7393090   59          19              0           0                   13
1  1215004   25           5              0           1                   10
2  8901342   50          12              0           2                   14
3  1944421   49           9              1           3                   12
4    13429   25          18              1           4                   11

#Lets split x,y, and train,test sets

In [31]:
X = ldnew.drop('risk_flag',axis=1)
Y = ldnew['risk_flag']
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=31)

In [32]:
xtrain.shape
ytrain.shape

(189000,)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

knn = KNeighborsClassifier(n_neighbors=17)
scores = cross_val_score(knn,xtrain,ytrain,scoring='roc_auc')
scores

array([0.88926524, 0.88983529, 0.88727405, 0.88874174, 0.88614783])

In [ ]:
knn = KNeighborsClassifier(n_neighbors=17)
knn.fit(xtrain,ytrain)
ypred = knn.predict(xtest)
roc_auc_score(ytest,ypred)

0.7518123603783472

In [ ]:
from sklearn.svm import LinearSVC
lsvc = LinearSVC()
scores = cross_val_score(lsvc,xtrain,ytrain,scoring='roc_auc')
scores

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarn

array([0.5133791 , 0.49710718, 0.52552606, 0.50251254, 0.49826398])

In [ ]:
from sklearn.svm import SVC
svc = SVC()
scores = cross_val_score(svc,xtrain,ytrain,scoring='roc_auc')
scores

array([0.50657365, 0.49730831, 0.50552217, 0.50592456, 0.49458117])

In [ ]:
from sklearn.svm import SVC
rvc = SVC()
#scores = cross_val_score(svc,xtrain,ytrain,scoring='roc_auc')
#scores

#Lets try Randomforest and check

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
scores = cross_val_score(DT,xtrain,ytrain,scoring='roc_auc')
scores

array([0.85027658, 0.85273439, 0.8511127 , 0.85563288, 0.84958367])

In [ ]:
lst = []
for x in range(20,60):
  DT =DecisionTreeClassifier(max_depth=x)
  DT.fit(xtrain,ytrain)
  ypred = DT.predict(xtest)
  lst.append((x,roc_auc_score(ytest,ypred)))

In [ ]:
lst

[(20, 0.7068534167454591),
 (21, 0.7200574790613992),
 (22, 0.7264379565023399),
 (23, 0.7303377000173414),
 (24, 0.7387348354921788),
 (25, 0.7414342480025359),
 (26, 0.746709863585805),
 (27, 0.7454629512202052),
 (28, 0.748730955432264),
 (29, 0.7519889546040993),
 (30, 0.7511712795273222),
 (31, 0.7529269323908457),
 (32, 0.7532774458105432),
 (33, 0.7531273070174657),
 (34, 0.7526153017169429),
 (35, 0.7528351177164597),
 (36, 0.752198765563393),
 (37, 0.752830115196348),
 (38, 0.753101515076932),
 (39, 0.7531042111719818),
 (40, 0.7528622577045181),
 (41, 0.7525827695387851),
 (42, 0.7529242362957962),
 (43, 0.7523063671380894),
 (44, 0.7520191803571952),
 (45, 0.7534262365560958),
 (46, 0.7524135790427983),
 (47, 0.7531756260959338),
 (48, 0.7532878405207541),
 (49, 0.7532724432904314),
 (50, 0.7528753485097787),
 (51, 0.7534986098575849),
 (52, 0.7531390497752014),
 (53, 0.7531765844734708),
 (54, 0.7523294629835734),
 (55, 0.7527613963674459),
 (56, 0.75274965360971),
 (57, 0.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
log_mod = LogisticRegression()
scores = cross_val_score(log_mod,xtrain,ytrain,scoring='roc_auc')
scores

array([0.50810495, 0.51314066, 0.50969233, 0.50441404, 0.49794459])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(max_features = 0.5,n_estimators=100)
scores = cross_val_score(RF,xtrain,ytrain,scoring='roc_auc')
scores

array([0.93634723, 0.93602928, 0.93588897, 0.93871755, 0.93618397])

In [ ]:
for x in range(20,61,5):
  for i in np.arange(0.1,1,0.2):
    rf = RandomForestClassifier(max_features = i,max_depth=x)
    rf.fit(xtrain,ytrain)
    ypred = rf.predict(xtest)
    print(x,i,roc_auc_score(ytest,ypred))

20 0.1 0.6822726863813141
20 0.30000000000000004 0.6825363876467369
20 0.5000000000000001 0.6717281954523996
20 0.7000000000000001 0.6728005251319132
20 0.9000000000000001 0.6675551353017397
25 0.1 0.73513584348629
25 0.30000000000000004 0.7377992483834646
25 0.5000000000000001 0.7189910154949427
25 0.7000000000000001 0.7189548288441981
25 0.9000000000000001 0.717463266916085
30 0.1 0.7474119330557072
30 0.30000000000000004 0.7482097770895995
30 0.5000000000000001 0.7459729133861984
30 0.7000000000000001 0.7419070651402472
30 0.9000000000000001 0.737917244668372
35 0.1 0.7483183370418331
35 0.30000000000000004 0.7483431706048295
35 0.5000000000000001 0.7493236856099571
35 0.7000000000000001 0.7481749384863797
35 0.9000000000000001 0.7470741207712828
40 0.1 0.7475553316111605
40 0.30000000000000004 0.7482346106525959
40 0.5000000000000001 0.7493806616811235
40 0.7000000000000001 0.7496886378824399
40 0.9000000000000001 0.7482088187120622
45 0.1 0.7469226339306806
45 0.30000000000000004 

KeyboardInterrupt: ignored

In [ ]:
rf = RandomForestClassifier(max_features = 0.1,max_depth=30)
rf.fit(X,Y)
ypred = rf.predict(ldnew_test)
write_report('new_rf_reg.csv')

In [ ]:
from sklearn.ensemble import BaggingClassifier
rf = RandomForestClassifier(max_features = 0.5)
bc = BaggingClassifier(n_estimators=50,base_estimator=rf)
bc.fit(xtrain,ytrain)
ypred = bc.predict(xtest)
roc_auc_score(ytest,ypred)

0.7485237141885647

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(loss='exponential')
gbc.fit(xtrain,ytrain)
ypred = gbc.predict(xtest)
roc_auc_score(ytest,ypred)

0.5004346294789221

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
dt = DecisionTreeClassifier()
abc = AdaBoostClassifier(base_estimator=dt,n_estimators=100)
abc.fit(xtrain,ytrain)
ypred = abc.predict(xtest)
roc_auc_score(ytest,ypred)

0.7523923683575248

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier(max_depth=30,learning_rate=0.1)
xgb.fit(xtrain,ytrain)
ypred = xgb.predict(xtest)
roc_auc_score(ytest,ypred)

0.7436305754956007

#Lets apply stratified cross validation and 

In [60]:
def skf_val(model):
  from sklearn.model_selection import StratifiedKFold
  skf = StratifiedKFold(n_splits=3)
  X = ldnew.drop('risk_flag',axis=1)
  Y = ldnew['risk_flag']
  for train_index, test_index in skf.split(X,Y):
    xtrain, xtest = X.loc[train_index,:],X.loc[test_index,:]
    ytrain, ytest = Y[train_index],Y[test_index]
    run_model(model)

#xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=31)

In [51]:
def run_model(model):
  knn = model
  knn.fit(xtrain,ytrain)
  ypred = knn.predict(xtest)
  print(d,roc_auc_score(ytest,ypred))

In [52]:
from sklearn.tree import DecisionTreeClassifier
for d in range(3,25):
  skf_val(DecisionTreeClassifier(max_depth=d))

3 0.5
3 0.5
3 0.5
3 0.5
3 0.5
4 0.5
4 0.5
4 0.5
4 0.5
4 0.5
5 0.5003287841191068
5 0.5003287841191068
5 0.5003627207706904
5 0.5003160122609838
5 0.5003160122609838
6 0.5007601080134287
6 0.5007261713618449
6 0.5007601080134287
6 0.5007601080134287
6 0.5007601080134287
7 0.5010680922493067
7 0.5011020289008904
7 0.5011020289008904
7 0.5010680922493067
7 0.5010680922493067
8 0.5025755364180412
8 0.5028415559772296
8 0.5026222449277478
8 0.5026237045686761
8 0.5024157057363888
9 0.5040997664574515
9 0.5042468252809809
9 0.5045000729820465
9 0.5042355130637863
9 0.5042114289884689
10 0.507214275288279
10 0.5073952707633922
10 0.5068960735659028
10 0.5073146256021018
10 0.5072595241570573
11 0.509982119398628
11 0.5103725733469566
11 0.5105043059407385
11 0.5103853452050796
11 0.5104364326375711
12 0.514097576996059
12 0.5145756094000875
12 0.5147595241570574
12 0.5144935045978689
12 0.5151331922347102
13 0.5178054298642534
13 0.5175580207269012
13 0.5182214275288279
13 0.5185345205079551


In [53]:
from sklearn.tree import DecisionTreeClassifier
for d in range(25,50):
  skf_val(DecisionTreeClassifier(max_depth=d))

25 0.540426944971537
25 0.5401339220551745
25 0.5430736388848343
25 0.5394997080718144
25 0.5416818712596702
26 0.5401302729528537
26 0.5390559772296015
26 0.5443460808641074
26 0.5393887753612611
26 0.5412596701211502
27 0.5424040286089621
27 0.542205152532477
27 0.5399416143628668
27 0.5427820756094002
27 0.5424193548387096
28 0.5404565027003356
28 0.5424481827470442
28 0.5427627353670996
28 0.5413716975623996
28 0.5415508684863524
29 0.5424806597576995
29 0.544762443438914
29 0.542227412056634
29 0.5396661071376441
29 0.5439592760180995
30 0.5409940154721938
30 0.5430517442709093
30 0.542992993723544
30 0.5403882644869362
30 0.5408681214421251
31 0.5414906582980586
31 0.5432298204641658
31 0.5420796234126405
31 0.5411085972850678
31 0.5428331630418917
32 0.5389505181725296
32 0.5427583564443146
32 0.5444088454240257
32 0.543023646183039
32 0.5430024813895782
33 0.5393365931980733
33 0.5438804554079697
33 0.5436396146547949
33 0.5430696248722814
33 0.5437031090351775
34 0.54140563421

In [55]:
from sklearn.tree import DecisionTreeClassifier
for d in range(25,50):
  skf_val(DecisionTreeClassifier(max_depth=d,criterion='entropy'))

25 0.530009122755802
25 0.5294442417165377
25 0.5283236023938112
25 0.5297982046416582
25 0.5287483579039556
26 0.5305736388848343
26 0.532099693475405
26 0.5320734199386951
26 0.5330320391183768
26 0.5322971099109619
27 0.5310888921325354
27 0.5346281564735075
27 0.5335078820610131
27 0.5324919719748942
27 0.5317880601372063
28 0.5340815209458474
28 0.5337392351481536
28 0.5358914756969785
28 0.5313808203182018
28 0.5336286673478324
29 0.5347697416435556
29 0.5338658589986863
29 0.5357320099255584
29 0.5328685593344037
29 0.5355185374397897
30 0.5355382425923223
30 0.5341296890964822
30 0.5360629835060575
30 0.5349419792730988
30 0.5357714202306233
31 0.5363366661801198
31 0.5350806451612904
31 0.5357294555539338
31 0.5374653335279521
31 0.5369592030360532
32 0.5348992847759452
32 0.5353813311925266
32 0.5363034593490003
32 0.5382564589111078
32 0.5362118668807474
33 0.536491753028755
33 0.5368245511604146
33 0.5369683257918553
33 0.5383323602393811
33 0.5366110786746461
34 0.53792986

In [59]:
from sklearn.ensemble import RandomForestClassifier
for d in range(25,50,3):
  skf_val(RandomForestClassifier(n_estimators=30,max_depth=d))

25 0.49606991680046714
25 0.4962454386220989
25 0.49582250766311486
25 0.4956229017661655
25 0.4967679900744417
28 0.496540286089622
28 0.4952386512917822
28 0.49574770106553784
28 0.4944081156035615
28 0.49662202598160854
31 0.49521201284484023
31 0.4960170048168151
31 0.4953178368121442
31 0.4950434243176179
31 0.4959830681652314
34 0.4956889505181726
34 0.49529667201868344
34 0.4953495840023355
34 0.49569442417165377
34 0.49641877098233833
37 0.4953532331046563
37 0.4956123193694352
37 0.4955174427090936
37 0.4947989344621223
37 0.49410706466209314
40 0.4971460370748796
40 0.49608487811998253
40 0.49546088162312074
40 0.49606115895489705
40 0.49567617866004965
43 0.49427127426653045
43 0.4956604875200701
43 0.4974321266968325
43 0.4959786892424464
43 0.4948595095606481
46 0.49608524303021456
46 0.49582469712450744
46 0.49552036199095023
46 0.4942654357028171
46 0.4963935921763246
49 0.4947040578017808
49 0.49575390453948326
49 0.496236680776529
49 0.4948540359071668
49 0.49825098525

In [61]:
from sklearn.ensemble import RandomForestClassifier
for d in range(25,50,3):
  skf_val(RandomForestClassifier(n_estimators=50,max_depth=d))

25 0.49507480659757697
25 0.49701175010947307
25 0.495510509414684
28 0.49521091811414397
28 0.49727120128448404
28 0.4965125529119836
31 0.4943920595533499
31 0.4946157495256167
31 0.4943541088892133
34 0.4951715078090789
34 0.4949281126842797
34 0.49538534520507954
37 0.49480221865421103
37 0.49518427966720185
37 0.4953583418479054
40 0.4954802218654211
40 0.4943438914027149
40 0.49530907896657417
43 0.49476134870821775
43 0.4953357174135163
43 0.49564698584148303
46 0.495286089621953
46 0.4955663406801927
46 0.49477266092541233
49 0.4966205663406802
49 0.4937133265216757
49 0.4956754488395854


In [64]:
from sklearn.neighbors import KNeighborsClassifier
for d in range(3,25,3):
  skf_val(KNeighborsClassifier(n_neighbors=d))

3 0.519375273682674
3 0.519375273682674
3 0.519375273682674
6 0.5159108159392789
6 0.5159108159392789
6 0.5159108159392789
9 0.5193818420668516
9 0.5193818420668516
9 0.5193818420668516
12 0.5173087870383885
12 0.5173087870383885
12 0.5173087870383885
15 0.5193687052984965
15 0.5193687052984965
15 0.5193687052984965
18 0.5183655670705006
18 0.5183655670705006
18 0.5183655670705006
21 0.5201558166690994
21 0.5201558166690994
21 0.5201558166690994
24 0.5181491753028754
24 0.5181491753028754
24 0.5181491753028754


In [65]:
from sklearn.ensemble import RandomForestClassifier
for d in range(3,50,5):
  skf_val(RandomForestClassifier(n_estimators=100,max_depth=d))

3 0.5
3 0.5
3 0.5
8 0.4998981900452489
8 0.4998868778280543
8 0.49986425339366514
13 0.4987968909648226
13 0.49885929061450884
13 0.49874032987884975
18 0.49649941614362864
18 0.49717705444460664
18 0.4970694059261421
23 0.49555064954021316
23 0.4946266968325792
23 0.49534848927163916
28 0.49401510728360826
28 0.4942314990512334
28 0.4947733907458765
33 0.4944508101007153
33 0.4938567362428843
33 0.49503101736972704
38 0.49496460370748796
38 0.49507225222595236
38 0.49444789081885854
43 0.49405342285797693
43 0.4938625748065976
43 0.4947664574514669
48 0.49496569843818417
48 0.49487118668807467
48 0.49516822361699026


In [67]:
from sklearn.ensemble import GradientBoostingClassifier
for d in np.arange(0.1,1,0.2):
  skf_val(GradientBoostingClassifier(learning_rate=d))

0.1 0.5000467085097067
0.1 0.500035396292512
0.1 0.5000467085097067
0.30000000000000004 0.5002922930958984
0.30000000000000004 0.5002470442271202
0.30000000000000004 0.500224419792731
0.5000000000000001 0.5033925704276748
0.5000000000000001 0.5035297766749379
0.5000000000000001 0.5034151948620639
0.7000000000000001 0.5006531893154285
0.7000000000000001 0.5006531893154285
0.7000000000000001 0.5008356444314699
0.9000000000000001 0.5027638300977959
0.9000000000000001 0.5025912275580207
0.9000000000000001 0.5026138519924098
