<a href="https://colab.research.google.com/github/shameer-phy/ML/blob/main/Hackathons/univ.ai/Loan_Default.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

In [3]:
from google.colab import drive 

drive.mount("/content/gdrive") 

Mounted at /content/gdrive


In [4]:
# Lets read the training dataset and tes dataset

ld = pd.read_csv('/content/gdrive/My Drive/Datasets/univ.ai/Training Data.csv')
 
ld_test = pd.read_csv('/content/gdrive/My Drive/Datasets/univ.ai/Test Data.csv')


In [5]:
ld.head()

ld.count()

ld.dtypes

Id                      int64
income                  int64
age                     int64
experience              int64
married                object
house_ownership        object
car_ownership          object
profession             object
city                   object
state                  object
current_job_years       int64
current_house_years     int64
risk_flag               int64
dtype: object

In [19]:
for x in ld.columns:
    print('\n')
    print(x)
    print(len(ld[x].unique()))
    print(ld[x].value_counts())



Id
252000
2047     1
64074    1
59976    1
37447    1
39494    1
        ..
95620    1
85379    1
83330    1
89473    1
2049     1
Name: Id, Length: 252000, dtype: int64


income
41917
7936020    77
9775375    71
1996629    71
9345456    70
7638998    40
           ..
5446449     1
7330601     1
3377955     1
2779935     1
7907349     1
Name: income, Length: 41917, dtype: int64


age
59
27    5197
66    5092
48    4967
33    4921
41    4827
45    4806
54    4785
68    4772
35    4644
50    4624
69    4617
76    4585
55    4563
25    4543
72    4534
79    4505
60    4504
59    4498
53    4490
47    4483
30    4468
78    4455
22    4430
34    4414
57    4394
58    4368
56    4344
24    4326
23    4322
62    4311
31    4257
70    4251
61    4235
40    4233
43    4206
21    4205
49    4203
26    4156
37    4153
71    4149
42    4134
64    4132
29    4109
67    3995
65    3969
74    3954
63    3942
77    3916
28    3901
32    3834
75    3829
39    3800
38    3793
46    3627
44    3622
73 

In [7]:
obj_cols = ld.select_dtypes(include=['object'])
obj_cols

married house_ownership  ...                 city           state
0        single          rented  ...                 Rewa  Madhya_Pradesh
1        single          rented  ...             Parbhani     Maharashtra
2       married          rented  ...            Alappuzha          Kerala
3        single          rented  ...          Bhubaneswar          Odisha
4        single          rented  ...  Tiruchirappalli[10]      Tamil_Nadu
...         ...             ...  ...                  ...             ...
251995   single          rented  ...              Kolkata     West_Bengal
251996   single          rented  ...                 Rewa  Madhya_Pradesh
251997   single          rented  ...      Kalyan-Dombivli     Maharashtra
251998   single          rented  ...          Pondicherry      Puducherry
251999   single          rented  ...                Avadi      Tamil_Nadu

[252000 rows x 6 columns]

In [8]:
for x in obj_cols.columns:
  ld[x] = pd.factorize(ld[x])[0]

In [10]:
ld.head()

Id   income  age  ...  current_job_years  current_house_years  risk_flag
0   1  1303835   23  ...                  3                   13          0
1   2  7574516   40  ...                  9                   13          0
2   3  3991815   66  ...                  4                   10          0
3   4  6256451   41  ...                  2                   12          1
4   5  5768871   47  ...                  3                   14          1

[5 rows x 13 columns]

In [11]:
for x in obj_cols.columns:
  ld_test[x] = pd.factorize(ld_test[x])[0]
ld_test.head()

id   income  age  ...  state  current_job_years  current_house_years
0   1  7393090   59  ...      0                  4                   13
1   2  1215004   25  ...      1                  5                   10
2   3  8901342   50  ...      1                  9                   14
3   4  1944421   49  ...      1                  3                   12
4   5    13429   25  ...      0                 13                   11

[5 rows x 12 columns]

#Lets split X,Y as well as train and test sets

In [13]:
X = ld.drop(['Id','risk_flag'],axis=1)
Y = ld['risk_flag']

In [45]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=13)

In [54]:
xtrain.shape
ytrain.shape
xtest.shape
ytest.shape

(63000,)

#Lets fit a Logistic model and check accuracy

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
log_mod = LogisticRegression()
scores = cross_val_score(log_mod,xtrain,ytrain,scoring='roc_auc')
scores


array([0.50196728, 0.49528195, 0.50506802, 0.50772664, 0.50412322])

In [55]:
ypred = log_mod.fit(xtrain,ytrain).predict(xtest)

In [56]:
roc_auc_score(ytest,ypred)

0.5

In [18]:
auc = cross_val_score(log_mod,X,Y,scoring='accuracy')
auc

array([0.87700397, 0.87700397, 0.87700397, 0.87700397, 0.87698413])

#Lets fit a DecisionTree and check

In [59]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
scores = cross_val_score(DT,xtrain,ytrain,scoring='roc_auc')
scores

array([0.84728045, 0.85074891, 0.85116217, 0.85294038, 0.8535443 ])

In [60]:
ypred = DT.fit(xtrain,ytrain).predict(xtest)
roc_auc_score(ytest,ypred)

0.7502545352325969

In [22]:
auc = cross_val_score(DT,X,Y,scoring='accuracy')
auc

array([0.93107143, 0.92253968, 0.90876984, 0.88700397, 0.73238095])

#Decions tree looks more promising than logistic
#Lets try Randomforest and check

In [61]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(max_features = 0.5,n_estimators=200)
scores = cross_val_score(RF,xtrain,ytrain,scoring='roc_auc')
scores

array([0.93747953, 0.93765926, 0.93854006, 0.93925197, 0.9372049 ])

In [62]:
ypred = RF.fit(xtrain,ytrain).predict(xtest)
roc_auc_score(ytest,ypred)

0.7410637183719415

In [64]:
ypred = RF.fit(xtrain,ytrain).predict(Xtest)

In [65]:
write_report('rf_output.csv')

In [44]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(max_features = 0.6,n_estimators=100)
auc_roc = cross_val_score(RF,X,Y,scoring='roc_auc')
auc_roc

array([0.97495546, 0.96832583, 0.95781029, 0.93612737, 0.65070217])

In [27]:
Xtest = ld_test.drop(['id'],axis=1)
RF = RandomForestClassifier(max_features = 0.5,n_estimators=100)
RF.fit(X,Y)
ypred = RF.predict(Xtest)

In [33]:
report = pd.concat([ld_test['id'],pd.DataFrame(ypred,columns=['risk_flag'])],axis=1)
report

id  risk_flag
0          1          0
1          2          0
2          3          0
3          4          0
4          5          0
...      ...        ...
27995  27996          0
27996  27997          0
27997  27998          0
27998  27999          0
27999  28000          0

[28000 rows x 2 columns]

In [37]:
report.to_csv('/content/gdrive/My Drive/Datasets/univ.ai/output.csv',index=False)

#Take the oupput file of logistic reg

In [39]:
log_mod = LogisticRegression()
log_mod.fit(X,Y)
ypred = log_mod.predict(Xtest)
report = pd.concat([ld_test['id'],pd.DataFrame(ypred,columns=['risk_flag'])],axis=1)
report.to_csv('/content/gdrive/My Drive/Datasets/univ.ai/logmod_output.csv',index=False)

In [41]:
#function to write report
def write_report(name):
  report = pd.concat([ld_test['id'],pd.DataFrame(ypred,columns=['risk_flag'])],axis=1)
  report.to_csv('/content/gdrive/My Drive/Datasets/univ.ai/' + name ,index=False)

In [42]:
write_report('logmod1.csv')

#Lets try KNN and check

In [66]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
scores = cross_val_score(knn,xtrain,ytrain,scoring='roc_auc')
scores

array([0.87032104, 0.86852591, 0.87168652, 0.87682959, 0.87263645])

In [68]:
knn.fit(xtrain,ytrain)
ypred = knn.predict(xtest)
roc_auc_score(ytest,ypred)

0.7249346451976036

#Lets try Naive Bayes and check

In [ ]:
from sklearn.naive_bayes